GET http://localhost:5000/api/users

### Register User
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "username": "pernilla",
  "email": "pernilla@test.com",
  "password": "pernilla"
}

### Login POST
POST http://localhost:5000/api/auth
Content-Type: application/json

{
  "email": "pernilla@test.com",
  "password": "pernilla"
}