GET http://localhost:5000/api/users

### POST - Register User
POST http://localhost:5000/api/register
Content-Type: application/json

{
  "username": "bella",
  "email": "bella@test.com",
  "password": "123456",
  "role": "user"
}

### POST ADMIN login admin user
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "123456"
}

### GET auth user
GET http://localhost:5000/api/auth/profile
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDMwNWVjOWYxNGM1NWNhMGY0MWMxMyIsImlhdCI6MTYzMTc5NDUyNywiZXhwIjoxNjMxNzk4MTI3fQ.ZxglMRuX8QrnFqheKeypf3_mlUMhbfKx1_kwVM2xDuY

### GET logout user token
GET http://localhost:5000/api/auth/logout
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDMwNWVjOWYxNGM1NWNhMGY0MWMxMyIsImlhdCI6MTYzMTc4NzQ0NSwiZXhwIjoxNjMxNzkxMDQ1fQ.6rAezo5LeLPS2Q2Ea4X4oG9O_P7yBawMies0BkFVcOI

### GET all user
GET http://localhost:5000/api/admin
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDMwNWVjOWYxNGM1NWNhMGY0MWMxMyIsImlhdCI6MTYzMTc5NDUyNywiZXhwIjoxNjMxNzk4MTI3fQ.ZxglMRuX8QrnFqheKeypf3_mlUMhbfKx1_kwVM2xDuY
### DELETE user :id
DELETE http://localhost:5000/api/admin/delete-user/614319b1886b9067814c21aa
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDMwNWVjOWYxNGM1NWNhMGY0MWMxMyIsImlhdCI6MTYzMTc4NzQ0NSwiZXhwIjoxNjMxNzkxMDQ1fQ.6rAezo5LeLPS2Q2Ea4X4oG9O_P7yBawMies0BkFVcOI

