const skills = [
  "Running",
  "Crossfit",
  "Yoga",
  "Triathlon",
  "Swimming",
  "HIIT",
  "Post pregnancy",
  "Weight lifting",
  "Weight loss",
  "Group training",
  "Tabat",
  "Rehad",
  "Senior",
  "Physiotheraphy",
  "Cardio",
  "Endurance",
  "Dietray advice",
  "Outdoor training",
  "Military training",
  "Swimrun",
  "Flexibility",
];

export default skills;
