const skills = [
  "Running",
  "Crossfit",
  "Yoga",
  "Triathlon",
  "Swimming",
  "HIIT",
  "Post pregnancy",
  "Weight-lifting",
  "Weight-loss",
  "Group training",
  "Tabat",
  "Rehab",
  "Senior-training",
  "Physiotherapy",
  "Cardio",
  "Endurance",
  "Dietary-advice",
  "Outdoor training",
  "Military training",
  "Swimrun",
  "Flexibility",
  "Cycling",
  "Boxing",
  "Pregnancy-training",
  "Meditation",
];

export default skills;
